# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Genevariation 3D"
email: "edeutsch@systemsbiology.org"
description: "A workshop to discuss interconnection of precision medicine, genetic variation data, protein sequence, and 3D structural information."
baseurl: ""
url: "http://genevariation3d.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-85181317-1"
googleAnalyticsSiteUrl: "genevariation3d.org"
siteVerification: "0p6-cgaWBJl3VReLF3lySDRuZ8G4huQfAX1SM4JqrBU"
isbImage: "isb.jpg"

# Organizer Info
organizerName: "genevariation3d.org"
organizerAlternateName: "Gene Variation 3D"
organizerDescription: "A Big Data Spoke Planning Grant and is part of the West Big Data Innovation Hub."
organizerEmail: "edeutsch@systemsbiology.org, andreas.prlic@rcsb.org"
organizerLogo: "/img/about-section/snp3d.png"
organizerLink: "http://genevariation3d.org"

# Head
metaKeywords: "event, gene variation, precision medicine, workshop, proteomics, genomics, 3D structure, big data, west big data hub"
twitterAccount: "@ericwdeutsch"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png?v=3"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png?v=3"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png?v=3"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"
registerUrl: "https://secure.qgiv.com/for/ifsbevents/event/778505/"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/schedule/", text: "Program"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/register/", text: "Registration"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/usecases/", text: "Use Cases"}
 - {permalink: "/resources/", text: "Resources"}
 - {permalink: "/team/", text: "Team"}

bottomNavigationLinks:
 - {link: "/register/", text: "Register"}
rightNavigationButtons:
 - {link: "/register/", text: "Register"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout> Gene Variation 3D Workshop 2017"
eventDate: "February 9th, 10th, 2017"
typeoutTextValues: '"", "Institute for Systems Biology", "Seattle", "Washington", "USA"'
typeoutFallback: "ISB"
heroButtons:
 - {permalink: "/register", text: "Register"}
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Gene Variation 3D Workshop"
aboutBlock:
 - {title: "Workshop", image: "conference.jpg", text: "A two-day workshop at the Institute for Systems Biology in Seattle, Washington, for researchers working toward the interconnection of precision medicine, genomic, proteomic, and protein structure data." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "40", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "2", specialCharacter: "+", info: "days", detail: "of Big Data technologies"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Institute for Systems Biology"
eventLocationLink: "https://www.systemsbiology.org"
eventStreetAddress: "401 Terry Ave N"
eventAddressLocality: "Seattle"
eventAddressLocalityRegion: "Washington"
eventPostalCode: "98109"
eventAddressCountry: "USA"
eventStartTime: "2016-02-09T08:00"
eventDoorTime: "09:00"
eventEndTime: "2016-02-10T20:00"
eventPlaceCoordinates: "47.62253, -122.33752 "
mapCenterCoordinates: "47.62253, -122.33752"
mapMobileCenterCoordinates: "47.62253, -122.33752"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Institute for Systems Biology"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "genevariation3d"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://genevariation3d.org/register/"
subscribeInfo: "Registration is open"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.rcsb.org", text: "www.rcsb.org"}
   - {link: "https://www.systemsbiology.org/", text: "Institute for Systems Biology"}
   - {link: "http://westbigdatahub.org/", text: "West Big Data Innovation Hub"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:andreas@rcsb,org", text: "andreas@rcsb.org"}
 -


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "genevariation3d"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "A two-day workshop at the Institute for Systems Biology in Seattle, Washington, for collaborators and other researchers working toward the interconnection of genomic, proteomic, and protein structure data. Our ultimate goal is to tie together genetic variation data with protein level information, by using the four established resources (and others, yet to be determined) as a driving force:"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "47.62253, -122.33752"
logisticsMapMobileCenterCoordinates: "47.62253, -122.33752"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Seattle"
directionDetailsCards:
 - {title: "Parking Options",
    information: 'There is no onsite parking available at ISB for event attendees. We recommend street parking or garages in the area. There are a variety of pay-to-park options nearby ISB you can use. Click to view <a href="https://en.parkopedia.com/parking/401_terry_ave_n_98109/">pay-to-park options</a>.<br/>

One nearby parking garage is located west of the ISB building. More info <a href="https://lots.impark.com/IMP/en?latlng=47.623028,-122.33819800000003&q=428 Westlake Ave N%2C Seattle%2C WA%2C United States&a=#details=25,48">here</a>. The early bird (in before 10am) daily rate is $15.00. '}
 - {title: "Driving Directions",
    information: '<h5>From Everett via I-5 S</h5> <p>Travel south on Interstate 5. Take the Mercer Exit 167 toward Seattle Center. Use the left 2 lanes to turn left onto Fairciew Ave N. Turn right onto Harrison St. Turn right onto Terry Ave N. Institute for Systems Biology will be on your left. </p>
<h5>From Olympia via I-5 N</h5><p>Travel north on Interstate 5. Take the Mercer Exit 167 toward Seattle Center. Use the left 2 lanes to turn left onto Fairciew Ave N. Turn right onto Harrison St. Turn right onto Terry Ave N. Institute for Systems Biology will be on your left. </p>'}

 - {title: "Hotels", information: 'Seattle has lots of great hotels and hostels. See below for a list of suggestions.'}
directionDetailsWideCards:
 -
  title: "Hotel Suggestions"
  subCards:
   -
    title: "Hotels"
    links:
     - {
        link: "http://www.hotelmaxseattle.com",
        text: "Hotel Max. Please utilize the corporate code IFSB on their website to enable the discount.",
        cost: "ISB Price: $249 per night",
        distance: ".9 mi",
        telephone: "(866) 833-6299"
        }
     - {
        link: "http://www.silvercloud.com/",
        text: "Silver Cloud Inn Lake Union",
        cost: "ISB Price: $229 (Q), $249 (K) per night",
        distance: ".8 mi",
        telephone: "(206) 812-4902"
        }
     - {
        link: "http://www.collegeinnseattle.com/",
        text: "College Inn Seattle",
        cost: "general prices: $100-130 per night",
        distance: "2.9 mi",
        note: "Rather spartan but nice accomodations 3 miles away, but the price is nice.Bus route #70 can be taken to get to ISB",
        telephone: "(206) 633-4441"
        }

# Hackathon
hackathonTitle: "Use Cases"
enableHackathon: true

# Hackathon About Block
aboutUseCaseTitle: "Use Cases"
useCases:
 - {
    title: "Genomic architecture of inflammatory bowel disease in five families with multiple affected individuals",
    image: "IBD_protein_structure.png",
    details: "This Big Data Spokes Project aims to speed our understanding of genetic variants that are suspected of causing disease by instantly showing researchers a 3D model of the chemical effect of each variant. Because determining these effects is currently a laborious process requiring specialized skills, it is often not done in research on genetic variants. Here, we present a study of the genetic causes of inflammatory bowel disease, and show how our resource could have been employed to make the study faster and cheaper. ",
    link: "https://docs.google.com/document/d/1NmLOUoMCbGqYZjB98Ta0WzcGRQFbzqy0_Fufy125V0Q/pub",
    citation: "http://www.nature.com/articles/hgv201560"
   }


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

# Members block
membersTitle: "Members"
members:
 - {title: "RCSB Protein Data Bank", link: "http://rcsb.org", image: "rcsb_logo.png", info: "The Protein Data Bank (PDB) is a crystallographic database for the three-dimensional structural data of large biological molecules, such as proteins and nucleic acids."}
 - {title: "Kaviar", link: "http://db.systemsbiology.org/kaviar", image: "KaviarLogo.png", info: "database of human genomic variation"}
 - {title: "PeptideAtlas", link: "http://www.peptideatlas.org", image: "PeptideAtlas_Logo.png", info: "proteomics data compendium"}
 - {title: "Trans-Proteomic Pipeline", link: "http://tools.proteomecenter.org/wiki/index.php?title=Software:TPP", image: "software.png", info: "Trans-Proteomic Pipeline software"}
